name: Commit Phase

on:
  push:
    branches:
      - main # or specify your desired branch

jobs:
  lint-build-test-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.16

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test (core unit tests)
        run: npm run test:unit

      - name: Archive Frontend
        id: frontend-build
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build-latest
          path: ./packages/frontend/dist
          # Customize Artifact Retention Period
          retention-days: 2
